services:
  #app es el nombre del servicio
  m_app_2:
    build:
      context: ./app 2
      dockerfile: Dockerfile
    ports:
     - "3500:80"

mysql:
  image: mysql:8.0
  container_name: mysql_prueba
  ports:
    - "3306:3306"